export const data = [
    {
      id: 1,
      question: "What is the capital of the Brazil? ",
      correct: 'Brasilia',
      answers: [
        { id:1,
          text: "Buenos Aires",
          correct: false,
        },
        { id:2,
          text: "Brasilia",
          correct: true,
        },
        { id:3,
          text: "Rido de Janeiro",
          correct: false,
        },
        { id:4,
          text: "São Paulo",
          correct: false,
        }
      ],
    },

    {
      id: 2,
      question: "What is the world's highest mountain?",
      correct:"Mount Everest",
      answers: [
        { id:1,
          text: "Mont Blanc",
          correct: false,
        },
        { id:2,
          text: "Mount Everest",
          correct: true,
        },
        { id:3,
          text: "K2",
          correct: false,
        },
        { id:4,
          text: "Denali",
          correct: false,
        },
      ],
    },

    {
      id: 3,
      question: "What continent is Mexico on? ",
      correct:"North America",
      answers: [
        { id:1,
          text: "Europe",
          correct: false,
        },
        { id:2,
          text: "North America",
          correct: true,
        },
        { id:3,
          text: "Asia",
          correct: false,
        },
        { id:4,
          text: "South America",
          correct: false,
        },
      ],
    },

    {
      id: 4,
      question: "What is the longest River in The World?",
      correct:"Nile River",
      answers: [
        { id:1,
          text: "Amazon River",
          correct: false,
        },
        { id:2,
          text: "Yellow River",
          correct: false,
        },
        { id:3,
          text: "Mississippi River",
          correct: false,
        },
        { id:4,
          text: "Nile River",
          correct: true,
        },
      ],
    },

    {
      id: 5,
      question: "What Is The Largest Continent?",
      correct:"Asia",
      answers: [
        { id:1,
          text: "Europe",
          correct: false,
        },
        { id:2,
          text: "North America",
          correct: false,
        },
        { id:3,
          text: "Asia",
          correct: true,
        },
        { id:4,
          text: "Africa",
          correct: false,
        },
      ],
    },

    {
      id: 6,
      question: "What Is The Official Language Of Brazil??",
      correct:"Portuguese",
      answers: [
        { id:1,
          text: "English",
          correct: false,
        },
        { id:2,
          text: "French",
          correct: false,
        },
        { id:3,
          text: "Spanish",
          correct: false,
        },
        { id:4,
          text: "Portuguese",
          correct: true,
        },
      ],
    }, 

    {
      id: 7,
      question: "How many countries are in the continent of Europe??",
      correct: "40-50,  There is 46 countries in Europe " ,
      answers: [
        { id:1,
          text: "10 - 20",
          correct: false,
        },
        { id:2,
          text: "20 - 30",
          correct: false,
        },
        { id:3,
          text: "30 - 40",
          correct: false,
        },
        { id:4,
          text: "40 - 50",
          correct: true,
        },
      ],
    },

    {
      id: 8,
      question: "What Is The Capital Of Australia??",
      correct:"Canberra",
      answers: [
        { id:1,
          text: "Canberra",
          correct: true,
        },
        { id:2,
          text: "Sydney",
          correct: false,
        },
        { id:3,
          text: "Brisbane",
          correct: false,
        },
        { id:4,
          text: "Australia city",
          correct: false,
        },
      ],
    },

    {
      id: 9,
      question: "What is the official language of Turkey?",
      correct:"Turkish",
      answers: [
        { id:1,
          text: "Arabic",
          correct: false,
        },
        { id:2,
          text: "Persian",
          correct: false,
        },
        { id:3,
          text: "Hindi",
          correct: false,
        },
        { id:4,
          text: "Turkish",
          correct: true,
        },
      ],
    },

    {
      id: 10,
      question: "What is the capital of Honduras?",
      correct: "Tegucigalpa",
      answers: [
        { id:1,
          text: "Lima",
          correct: false,
        },
        { id:2,
          text: "Tegucigalpa",
          correct: true,
        },
        { id:3,
          text: "Managua",
          correct: false,
        },
        { id:4,
          text: "San José",
          correct: false,
        },
      ],
    }, 
  ]


 export const data1 = [
  {
    id: 1,
    question: "What is smallest country in the world ?",
    correct: "Vatikan City" ,
    answers: [
      { id:1,
        text: "Liechtenstein",
        correct: false,
      },
      { id:2,
        text: "Nauru",
        correct: false,
      },
      { id:3,
        text: "Monaco",
        correct: false,
      },
      { id:4,
        text: "Vatican City",
        correct: true,
      },
    ],
  },

  {
    id: 2,
    question: "How many official languages are there in Spain??",
    correct:"5",
    answers: [
      { id:1,
        text: "2",
        correct: false,
      },
      { id:2,
        text: "3",
        correct: false,
      },
      { id:3,
        text: "4",
        correct: false,
      },
      { id:4,
        text: "5",
        correct: true,
      },
    ],
  },

  {
    id: 3,
    question: "What is the capital of Kazakhstan?",
    correct:"Astana",
    answers: [
      { id:1,
        text: "Astana",
        correct: true,
      },
      { id:2,
        text: "Tashkent",
        correct: false,
      },
      { id:3,
        text: "Bishkek",
        correct: false,
      },
      { id:4,
        text: "Baku",
        correct: false,
      },
    ],
  },

  {
    id: 4,
    question: "The two major rivers in India are ",
    correct: "Ganges and Indus",
    answers: [
      { id:1,
        text: "Ganges and Indus",
        correct: true,
      },
      { id:2,
        text: "Ganges and Yellow",
        correct: false,
      },
      { id:3,
        text: "Indus and Volga",
        correct: false,
      },
      { id:4,
        text: "Indus and Yellow",
        correct: false,
      },
    ],
  }, 


{
  id: 5,
  question: "What is the capital of the Lithuania? ",
  correct:"Vilnius",
  answers: [
    { id:1,
      text: "Riga",
      correct: false,
    },
    { id:2,
      text: "Vilnius",
      correct: true,
    },
    { id:3,
      text: "Minsk",
      correct: false,
    },
    { id:4,
      text: "Tallinn",
      correct: false,
    }
  ],
},

{
  id: 6,
  question: "What is the capital of Turkmenistan?",
  correct:"Ashgaba",
  answers: [
    { id:1,
      text: "Tashkent",
      correct: false,
    },
    { id:2,
      text: "Kabul",
      correct: false,
    },
    { id:3,
      text: "Ashgabat",
      correct: true,
    },
    { id:4,
      text: "Sana'a",
      correct: false,
    } ] },

    {
      id: 7,
      question: "Which of the following is NOT part of the Amazon rainforest?",
      correct:"Paraguay",
      answers: [
        { id:1,
          text: "Paraguay",
          correct: true,
        },
        { id:2,
          text: "Bolivia",
          correct: false,
        },
        { id:3,
          text: "Brazil",
          correct: false,
        },
        { id:4,
          text: "Peru",
          correct: false,
        } ] },
        {
          id: 8,
          question: "What is the capital of Kansas?",
          correct:"Topeka",
          answers: [
            { id:1,
              text: "Wichita",
              correct: false,
            },
            { id:2,
              text: "Tucson",
              correct: false,
            },
            { id:3,
              text: "Pierre",
              correct: false,
            },
            { id:4,
              text: "Topeka",
              correct: true,
            } ] },
            {
              id: 9,
              question: "Swahili is a lingua franca in?",
              correct:"East Africa",
              answers: [
                { id:1,
                  text: "North Africa",
                  correct: false,
                },
                { id:2,
                  text: "East Africa",
                  correct: true,
                },
                { id:3,
                  text: "South Asia",
                  correct: false,
                },
                { id:4,
                  text: "Southwest Asia",
                  correct: false,
                } ] },
                {
                  id: 10,
                  question: "What is the capital of Ethiopia?",
                  correct:"Addis Ababa",
                  answers: [
                    { id:1,
                      text: "Addis Ababa",
                      correct: true,
                    },
                    { id:2,
                      text: "Mogadishu",
                      correct: false,
                    },
                    { id:3,
                      text: "Nairobi",
                      correct: false,
                    },
                    { id:4,
                      text: "Sana'a",
                      correct: false,
                    } ] },
  
 ]